# Generic settings
markdown: kramdown
highlighter: pygments
exclude:
  - "CNAME"
  - "Gemfile*"
  - "*.sh"
  - "browserslist"
  - "README.md"
  - ".idea/"
  - ".git/"
  - "scripts/"
  - "_site/"
  - "vendor/"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

collections:
  projects:
    output: true
    permalink: /projekte/:path/

permalink: blog/:year/:month/:title/

# languages: ["hr", "en"]

languages:
  -
    - en
    - English
  -
    - hr
    - hrvatski

# exclude_from_localizations: ["static", "files", "style", "js", "fonts", "images", "search.json"]

tag_page_layout: tag_index

tag_page_dir: blog/tags

tag_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed

kramdown:
  smart_quotes: ["ldquo", "rsquo", "bdquo", "ldquo"]

# Site settings
brand_full: Hrvatska udruga za otvorene sustave i internet
brand_small: Otvoreni sustavi
brand_full_en: Croatian Society for Open System and Internet
brand_small_en: HrOpen
baseurl: 'http://schlos.github.io/openhr'
url: 'http://schlos.github.io/openhr'
staticurl: /static/
default_lang: hr
github_user:  codeforcroatia
github_repo:  openhr

# Team 

team:
  -
      name: Xcvu Y2h
      img: xcvuy2h
      position_hr: Predsjednik
      position_en: President
      bio_hr: "xcvuy2h"
      bio_en: "xcvuy2h"
      staff: 0
      steering_committee: 1
      supervisory_board: 0
      advisory_board: 0
      mail: xcvuy2h@xcvuy2h.hh
      twitter: xcvuy2h
      website: http://xcvuy2h.hh
      github: xcvuy2h
  -
      name: Xcvu Y3h
      img: xcvuy2h
      position_hr: Dopredsjednik
      position_en: Vicepresident
      bio_hr: "xcvuy2h"
      bio_en: "xcvuy2h"
      staff: 0
      steering_committee: 1
      supervisory_board: 0
      advisory_board: 0
      mail: xcvuy2h@xcvuy2h.hh
      twitter: xcvuy2h
      website: http://xcvuy2h.hh
      github: xcvuy2h

# Bodies and members

advisory_board:

steering_committee:
  -
      name: Xcvu Y2h
  -
      name: Y
  -
      name: P
  -
      name: m

supervisory_board:
  -
      name: Anamarija
      mail: 
  -
      name: Ina
      mail: 
  -
      name: Lucija
      mail: 
  -
      name: Dubravka
      mail: 

# Menu

top_menu:
  - topics
  - projects
  - blog
  - services
  - donate
  
bottom_menu:
  - team
  - board
  - organisation
  - press
  - jobs
  - contact
  
# Metadata

meta:
  top_menu:
    label: top_menu
    output: true
    has_translation: true
    translate_link: true
    title: Glavni izbornik
    languages:
      - hr
    toc:
      entry_point: 'index'
      order:
        - topics
        - projects
        - blog
        - services
        - donate
      chapters:
        - title: 'Teme'
          slug: 'topics'
        - title: 'Projekti'
          slug: 'projects'
        - title: 'Blog'
          slug: 'blog'
        - title: 'Usluge'
          slug: 'services'
        - title: "Doniraj"
          slug: 'donate'
  bottom_menu:
    label: bottom_menu
    output: true
    has_translation: true
    translate_link: true
    title: Mali izbornik
    languages:
      - hr
    toc:
      entry_point: 'index'
      order:
        - team
        - board
        - organisation
        - press
        - jobs
        - contact
      chapters:
        - title: 'Tim'
          slug: 'team'
        - title: 'Tijela'
          slug: 'tijela'
        - title: 'Udruga'
          slug: 'organisation'
        - title: 'Press'
          slug: 'press'
        - title: "Poslovi"
          slug: 'jobs'
        - title: "Kontakt"
          slug: 'contact'
  contribute:
    label: contribute
    output: true
    title: Contribute
    has_translation: false
    toc:
      chapters:
        - title: 'Contributing'
        - title: 'Adding A Page'
          slug: 'adding'
        - title: 'Editing A Page'
          slug: 'editing'
        - title: 'Adding A Term To The Glossary'
          slug: 'add-term'
        - title: 'Adding A Resource To The Library'
          slug: 'add-resource'
        - title: 'Translating The Pages'
          slug: 'translate-guide'
        - title: 'Translating The Glossary'
          slug: 'translate-glossary'
        - title: 'Markdown Examples'
          slug: 'markdown-examples'
