markdown: kramdown
highlighter: pygments
fullurl: 'http://schlos.github.io/open.hr'
url: '/open.hr'
staticurl: /static/
exclude:
  - "CNAME"
  - "Gemfile*"
  - "*.sh"
  - "browserslist"
  - "Readme.md"
  - ".idea/"
  - ".git/"
  - "scripts/"
  - "_site/"
  - "vendor/"
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
collections:
  projects:
    output: true
    permalink: /projekte/:path/
permalink: blog/:year/:month/:title/
languages: ["hr", "en"]
exclude_from_localizations: ["static", "files", "style", "js", "fonts", "images", "search.json"]
tag_page_layout: tag_index
tag_page_dir: blog/tags
tag_permalink_style: pretty
sass:
  sass_dir: static/style/_scss
  style: compressed
kramdown:
  smart_quotes: ["ldquo", "rsquo", "bdquo", "ldquo"]
