# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#
title: HrOpen
tagline: Otvoreni za partnerstvo jer znamo kako
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
archive_description: Arhivska građa Udruge
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_repo: imamopravoznati-admin # the GitHub repo name for this project
#
# Site metadata
full_title: Hrvatska udruga za otvorene sustave i internet
#
# Site contact details
owner: Hrvatska udruga za otvorene sustave i internet
email: name@example.com
address:
  - line: Unska 3
  - line: "10000 Zagreb, Hrvatska"
  # Feel free to add more lines here 
telephone: + 385 (0)1 6129 660
#
# Company registration and bank information
org:
  bank:
    name: Zagrebačka banka d.d.
    address: "Trg bana Josipa Jelačića 10, 10000 Zagreb, Hrvatska"
    account:
      type: žiro račun
      iban: HR5023600001101557175
      swift: ZABAHR2X
      vbdi: 2360000
  registration:
    oib: 09913557986
    mb: 1602845
    vat: HR09913557986
# 
# Content on this website is licensed under a 
license_name: Creative Commons Attribution-ShareAlike 4.0 International License
license_url: http://creativecommons.org/licenses/by-sa/4.0/deed.en_US
# Copyright - leave blank to use open license instead
copyright:
# 
# Optional social link, you can fill in below usernames
# leave blank if you dont have account
facebook_username: example
twitter_username:
github_username: example
#
# API settings
google_api_key: AIzaSyA8H0jVz_6Hc273rqNYKQ6AAiBvQfVKmYQ
#
# Build settings
markdown: kramdown
#
# Set theme color here for archive site
# Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow; violet (custom).
theme_color: blue
#
# Site analytics
analytics:
  provider: google
  google:
    id: UA-46708458-XX